## server.R ##

  shinyServer(
    function(input, output) { 
      
      ## REACTIVE SUBSETS ## 
      # Generated by reactive expressions to cache selected values 
      
      sisInput <- reactive({  
        scrub_sis %<>% 
          filter(as.Date(sis_date) >= input$dateRange[1]
                 & as.Date(sis_date) <= input$dateRange[2])
      })
      
      tos1Input <- reactive({
        s1_tos <-
          sisInput() %>%
          filter(is.na(fake_id) == FALSE) %>% # Remove empty randomized IDs
          group_by(fake_id) %>% 
          filter(as.Date(sis_date) == max(as.Date(sis_date))) %>% # Most recent per ID
          ungroup() %>% droplevels() %>%
          select(fake_id,agency,ends_with("tos")) %>% 
          select(fake_id,agency,starts_with("s1")) %>%
          mutate_each(funs(as.character), -fake_id, -agency) %>%
          gather(field, tos, s1a_1_tos:s1f_8_tos) %>%
          rename(type = tos 
          ) %>%
          mutate(type_n = as.numeric(type),
                 field = gsub("tos","",field),
                 id = as.factor(paste0(fake_id,field))
          ) %>%
          group_by(id, agency, field, type) %>%
          summarize(n = n_distinct(id),
                    type_n = sum(type_n)) %>%
          ungroup() 
        
        s1_fqy <-
          sisInput() %>%
          filter(is.na(fake_id) == FALSE) %>% # Remove empty Medicaid IDs
          group_by(fake_id) %>% 
          filter(as.Date(sis_date) == max(as.Date(sis_date))) %>% # Most recent per ID
          ungroup() %>% droplevels() %>%
          select(fake_id,agency,ends_with("fqy")) %>% 
          select(fake_id, agency, starts_with("s1")) %>%
          mutate_each(funs(as.character), -fake_id, -agency) %>%
          gather(field, fqy, s1a_1_fqy:s1f_8_fqy) %>%
          rename(frequency = fqy) %>%
          mutate(frequency_n = as.numeric(frequency),
                 field = gsub("fqy","",field),
                 id = as.factor(paste0(fake_id,field))
          ) %>%
          group_by(id,agency, field, frequency) %>%
          summarize(frequency_n = sum(frequency_n)) %>%
          ungroup() 
        
        s1_dst <-
          sisInput() %>%
          filter(is.na(fake_id) == FALSE) %>% # Remove empty Medicaid IDs
          group_by(fake_id) %>% 
          filter(as.Date(sis_date) == max(as.Date(sis_date))) %>% # Most recent per ID
          ungroup() %>% droplevels() %>%
          select(fake_id,agency,ends_with("dst")) %>% 
          select(fake_id, agency, starts_with("s1")) %>%
          mutate_each(funs(as.character), -fake_id, -agency) %>%
          gather(field, dst, s1a_1_dst:s1f_8_dst) %>%
          rename(DST = dst) %>%
          mutate(DST_n = as.numeric(DST),
                 field = gsub("dst","",field),
                 id = as.factor(paste0(fake_id,field))
          ) %>%
          group_by(id,agency, field, DST) %>%
          summarize(DST_n = sum(DST_n)) %>%
          ungroup() 
        
        # Join intermediate tables
        s1 <- s1_tos %>% inner_join(s1_fqy, by = "id")
        s1 <- s1 %>% inner_join(s1_dst, by = "id")
        
        # Remove intermediate tables
        rm(s1_dst)
        rm(s1_fqy)
        rm(s1_tos)
        
        # Remove extra cols and recode vars  
        s1 <-
          s1 %>%
          select(id,agency,field,type,type_n,frequency,frequency_n,DST,DST_n) %>%
          mutate(field = car::recode(field,
                                     "'s1a_1_' = 'Toilet';
                                     's1a_2_' = 'Clothes';
                                     's1a_3_' = 'Preparing food';
                                     's1a_4_' = 'Eating food';
                                     's1a_5_' = 'Housekeeping';
                                     's1a_6_' = 'Dressing';
                                     's1a_7_' = 'Hygiene';
                                     's1a_8_' = 'Appliances';
                                     's1b_1_' = 'Getting Around';
                                     's1b_2_' = 'Recreation';
                                     's1b_3_' = 'Public Services';
                                     's1b_4_' = 'Visit Friends/Family';
                                     's1b_5_' = 'Preferred Activities';
                                     's1b_6_' = 'Shopping';
                                     's1b_7_' = 'Community interaction';
                                     's1b_8_' = 'Accessing Settings';
                                     's1c_1_' = 'Learning interaction';
                                     's1c_2_' = 'Learning decisions';
                                     's1c_3_' = 'Problem solving';
                                     's1c_4_' = 'Using technology';
                                     's1c_5_' = 'Accessing training';
                                     's1c_6_' = 'Academics';
                                     's1c_7_' = 'Learning health skills';
                                     's1c_8_' = 'Learning self-determination';
                                     's1c_9_' = 'Learning self-management';
                                     's1d_1_' = 'Job accomodations';
                                     's1d_2_' = 'Specific job skills';
                                     's1d_3_' = 'Co-worker interaction';
                                     's1d_4_' = 'Supervisor interaction';
                                     's1d_5_' = 'Work speed';
                                     's1d_6_' = 'Work quality';
                                     's1d_7_' = 'Changing assignments';
                                     's1d_8_' = 'Seeking assistance';
                                     's1e_1_' = 'Taking medications';
                                     's1e_2_' = 'Avoiding hazards';
                                     's1e_3_' = 'Obtaining health care';
                                     's1e_4_' = 'Moving about';
                                     's1e_5_' = 'Accessing emergency svs';
                                     's1e_6_' = 'Nutritional diet';
                                     's1e_7_' = 'Physical fitness';
                                     's1e_8_' = 'Emotional well-being';
                                     's1f_1_' = 'Socializing in home';
                                     's1f_2_' = 'Recreation with others';
                                     's1f_3_' = 'Socializing out of home';
                                     's1f_4_' = 'Making friends';
                                     's1f_5_' = 'Communicating with helpers';
                                     's1f_6_' = 'Appropriate social skills';
                                     's1f_7_' = 'Intimate relationships';
                                     's1f_8_' = 'Volunteer work';"),
                 type = car::recode(type,
                                    "'0' = 'None';
                                    '1' = 'Monitoring';
                                    '2' = 'Coaching';
                                    '3' = 'Partial Physical Assistance';
                                    '4' = 'Full Physical Support'"),
                 frequency = car::recode(frequency,
                                         "'0' = 'Minimal';
                                         '1' = 'Monthly';
                                         '2' = 'Weekly';
                                         '3' = 'Daily';
                                         '4' = 'Hourly'"),
                 DST = car::recode(DST,
                                   "'0' = 'None';
                                   '1' = 'Under 30 min';
                                   '2' = 'Under 2 hrs';
                                   '3' = '2-4 hrs';
                                   '4' = 'Over 4 hrs'")) 
        
        # Summarize for app
        
        tos_section1 <-
          s1 %>%
          group_by(agency, field, type, frequency, DST) %>%
          summarize(n = n(),
                    type_tot = sum(type_n),
                    frequency_tot = sum(frequency_n),
                    DST_tot = sum(DST_n)) %>%
          ungroup()
        
      })
      
      tos2Input <- reactive({
        
        # Make intermediate long form tables
        
        s2_tos <-
          sisInput() %>%
          filter(is.na(fake_id) == FALSE) %>% # Remove empty Medicaid IDs
          group_by(fake_id) %>% 
          filter(as.Date(sis_date) == max(as.Date(sis_date))) %>% # Most recent per ID
          ungroup() %>% droplevels() %>%
          select(fake_id,agency,ends_with("tos")) %>% 
          select(fake_id,agency,starts_with("s2")) %>%
          mutate_each(funs(as.character), -fake_id, -agency) %>%
          gather(field, tos, s2_1_tos:s2_8_tos) %>%
          rename(type = tos #, frequency = fqy, DST = dst
          ) %>%
          mutate(type_n = as.numeric(type),
                 field = gsub("tos","",field),
                 id = as.factor(paste0(fake_id,field))
          ) %>%
          group_by(id, agency, field, type) %>%
          summarize(n = n_distinct(id),
                    type_n = sum(type_n)) %>%
          ungroup() 
        
        
        s2_fqy <-
          sisInput() %>%
          filter(is.na(fake_id) == FALSE) %>% # Remove empty Medicaid IDs
          group_by(fake_id) %>% 
          filter(as.Date(sis_date) == max(as.Date(sis_date))) %>% # Most recent per ID
          ungroup() %>% droplevels() %>%
          select(fake_id,agency,ends_with("fqy")) %>% 
          select(fake_id, agency, starts_with("s2")) %>%
          mutate_each(funs(as.character), -fake_id, -agency) %>%
          gather(field, fqy, s2_1_fqy:s2_8_fqy) %>%
          rename(frequency = fqy) %>%
          mutate(frequency_n = as.numeric(frequency),
                 field = gsub("fqy","",field),
                 id = as.factor(paste0(fake_id,field))
          ) %>%
          group_by(id,agency, field, frequency) %>%
          summarize(frequency_n = sum(frequency_n)) %>%
          ungroup() 
        
        s2_dst <-
          sisInput() %>%
          filter(is.na(fake_id) == FALSE) %>% # Remove empty Medicaid IDs
          group_by(fake_id) %>% 
          filter(as.Date(sis_date) == max(as.Date(sis_date))) %>% # Most recent per ID
          ungroup() %>% droplevels() %>%
          select(fake_id,agency,ends_with("dst")) %>% 
          select(fake_id, agency, starts_with("s2")) %>%
          mutate_each(funs(as.character), -fake_id, -agency) %>%
          gather(field, dst, s2_1_dst:s2_8_dst) %>%
          rename(DST = dst) %>%
          mutate(DST_n = as.numeric(DST),
                 field = gsub("dst","",field),
                 id = as.factor(paste0(fake_id,field))
          ) %>%
          group_by(id,agency, field, DST) %>%
          summarize(DST_n = sum(DST_n)) %>%
          ungroup() 
        
        # Join intermediate tables
        s2 <- s2_tos %>% inner_join(s2_fqy, by = "id")
        s2 <- s2 %>% inner_join(s2_dst, by = "id")
        
        # Remove intermediate tables
        rm(s2_dst)
        rm(s2_fqy)
        rm(s2_tos)
        
        # Remove extra cols and recode vars  
        s2 <-
          s2 %>%
          select(id,agency,field,type,type_n,frequency,frequency_n,DST,DST_n) %>%
          mutate(field = car::recode(field,
                                     "'s2_1_' = 'Self-advocacy';
                                     's2_2_' = 'Money management';
                                     's2_3_' = 'Exploited by others';
                                     's2_4_' = 'Legal responsibility';
                                     's2_5_' = 'Participation';
                                     's2_6_' = 'Legal services';
                                     's2_7_' = 'Decision making';
                                     's2_8_' = 'Other advocacy'"),
                 type = car::recode(type,
                                    "'0' = 'None';
                                    '1' = 'Monitoring';
                                    '2' = 'Coaching';
                                    '3' = 'Partial Physical Assistance';
                                    '4' = 'Full Physical Support'"),
                 frequency = car::recode(frequency,
                                         "'0' = 'Minimal';
                                         '1' = 'Monthly';
                                         '2' = 'Weekly';
                                         '3' = 'Daily';
                                         '4' = 'Hourly'"),
                 DST = car::recode(DST,
                                   "'0' = 'None';
                                   '1' = 'Under 30 min';
                                   '2' = 'Under 2 hrs';
                                   '3' = '2-4 hrs';
                                   '4' = 'Over 4 hrs'")) 
        
        # Summarize for app
        
        tos_section2 <-
          s2 %>%
          group_by(agency, field, type, frequency, DST) %>%
          summarize(n = n(),
                    type_tot = sum(type_n),
                    frequency_tot = sum(frequency_n),
                    DST_tot = sum(DST_n)) %>%
          ungroup()
        
      })
      
      sec1Input <- reactive({
        
        sec1Input <-
          sisInput() %>%
          filter(is.na(fake_id) == FALSE) %>% # Remove empty Medicaid IDs
          group_by(fake_id) %>% 
          filter(as.Date(sis_date) == max(as.Date(sis_date))) %>% # Most recent per ID
          ungroup() %>% droplevels() %>%
          select(fake_id, agency,contains("s1")) %>%
          select(fake_id, agency, contains("tos"), contains("fqy"), contains("dst")) %>%
          gather(field, score, s1a_1_tos:s1f_8_dst) %>%
          mutate(item = gsub("tos|fqy|dst", "", field)) %>%
          group_by(fake_id, agency, item) %>%
          summarize(score = sum(score)) %>%
          mutate(item = car::recode(item,
                                    "'s1a_1_' = 'Toilet';
                                    's1a_2_' = 'Clothes';
                                    's1a_3_' = 'Preparing food';
                                    's1a_4_' = 'Eating food';
                                    's1a_5_' = 'Housekeeping';
                                    's1a_6_' = 'Dressing';
                                    's1a_7_' = 'Hygiene';
                                    's1a_8_' = 'Appliances';
                                    's1b_1_' = 'Getting Around';
                                    's1b_2_' = 'Recreation';
                                    's1b_3_' = 'Public Services';
                                    's1b_4_' = 'Visit Friends/Family';
                                    's1b_5_' = 'Preferred Activities';
                                    's1b_6_' = 'Shopping';
                                    's1b_7_' = 'Community interaction';
                                    's1b_8_' = 'Accessing Settings';
                                    's1c_1_' = 'Learning interaction';
                                    's1c_2_' = 'Learning decisions';
                                    's1c_3_' = 'Problem solving';
                                    's1c_4_' = 'Using technology';
                                    's1c_5_' = 'Accessing training';
                                    's1c_6_' = 'Academics';
                                    's1c_7_' = 'Learning health skills';
                                    's1c_8_' = 'Learning self-determination';
                                    's1c_9_' = 'Learning self-management';
                                    's1d_1_' = 'Job accomodations';
                                    's1d_2_' = 'Specific job skills';
                                    's1d_3_' = 'Co-worker interaction';
                                    's1d_4_' = 'Supervisor interaction';
                                    's1d_5_' = 'Work speed';
                                    's1d_6_' = 'Work quality';
                                    's1d_7_' = 'Changing assignments';
                                    's1d_8_' = 'Seeking assistance';
                                    's1e_1_' = 'Taking medications';
                                    's1e_2_' = 'Avoiding hazards';
                                    's1e_3_' = 'Obtaining health care';
                                    's1e_4_' = 'Moving about';
                                    's1e_5_' = 'Accessing emergency svs';
                                    's1e_6_' = 'Nutritional diet';
                                    's1e_7_' = 'Physical fitness';
                                    's1e_8_' = 'Emotional well-being';
                                    's1f_1_' = 'Socializing in home';
                                    's1f_2_' = 'Recreation with others';
                                    's1f_3_' = 'Socializing out of home';
                                    's1f_4_' = 'Making friends';
                                    's1f_5_' = 'Communicating with helpers';
                                    's1f_6_' = 'Appropriate social skills';
                                    's1f_7_' = 'Intimate relationships';
                                    's1f_8_' = 'Volunteer work';"))
        
      })
      
      sec2Input <- reactive({
        
        sec2Input <-
          sisInput() %>%
          filter(is.na(fake_id) == FALSE) %>% # Remove empty Medicaid IDs
          group_by(fake_id) %>% 
          filter(as.Date(sis_date) == max(as.Date(sis_date))) %>% # Most recent per ID
          ungroup() %>% droplevels() %>%
          select(fake_id,agency,s2_1_fqy:s2_8_for) %>%
          select(fake_id, agency, contains("tos"), contains("fqy"), contains("dst")) %>%
          gather(field, score, s2_1_tos:s2_8_dst) %>%
          mutate(item = gsub("tos|fqy|dst", "", field)) %>%
          group_by(fake_id, agency, item) %>%
          summarize(score = sum(score)) %>%
          mutate(item = car::recode(item,
                                    "'s2_1_' = 'Self-advocacy';
                                     's2_2_' = 'Money management';
                                     's2_3_' = 'Exploited by others';
                                     's2_4_' = 'Legal responsibility';
                                     's2_5_' = 'Participation';
                                     's2_6_' = 'Legal services';
                                     's2_7_' = 'Decision making';
                                     's2_8_' = 'Other advocacy'"))
        
      })

      sec3Input <- reactive({
        
        sisInput() %>%
          select(fake_id, agency, LivingType, starts_with("s3")) %>%
          select(fake_id, agency, LivingType, ends_with("support")) %>%
          gather(item,score,s3a_1_support:s3b_13_support) %>%
          mutate(subtype = car::recode(item,
                                       "c('s3a_1_support','s3a_2_support','s3a_3_support',
                                       's3a_4_support') = 'Respiratory Care';
                                       c('s3a_5_support','s3a_6_support',
                                       's3a_7_support') = 'Feeding Assistance';
                                       c('s3a_8_support','s3a_9_support') = 'Skin Care';
                                       c('s3a_10_support','s3a_11_support','s3a_12_support',
                                       's3a_13_support','s3a_14_support','s3a_15_support',
                                       's3a_16_support') = 'Other Medical';
                                       c('s3b_1_support','s3b_2_support','s3b_3_support') 
                                       = 'External Destructiveness';
                                       c('s3b_4_support','s3b_5_support','s3b_6_support') 
                                       = 'Self Destructiveness';
                                       c('s3b_7_support','s3b_8_support') = 'Sexual';
                                       c('s3b_9_support','s3b_10_support',
                                       's3b_11_support','s3b_12_support',
                                       's3b_13_support') = 'Other Behavioral'"),
                 type = car::recode(subtype,
                                    "c('Respiratory Care','Feeding Assistance',
                                    'Skin Care','Other Medical') = 'Medical';
                                    c('External Destructiveness','Self Destructiveness',
                                    'Sexual','Other Behavioral') = 'Behavioral'"),
                 name = car::recode(item,
                                    "'s3a_1_support' = 'Oxygen therapy';
                                    's3a_2_support' = 'Postural drainage';
                                    's3a_3_support' = 'Chest PT';
                                    's3a_4_support' = 'Suctioning';
                                    's3a_5_support' = 'Oral stimulation';
                                    's3a_6_support' = 'Tube feeding';
                                    's3a_7_support' = 'Parental feeding';
                                    's3a_8_support' = 'Positioning';
                                    's3a_9_support' = 'Dressing wounds';
                                    's3a_10_support' = 'Prevent infection';
                                    's3a_11_support' = 'Seizure mgmt';
                                    's3a_12_support' = 'Dialysis';
                                    's3a_13_support' = 'Ostomy care';
                                    's3a_14_support' = 'Transfers';
                                    's3a_15_support' = 'Therapy svs';
                                    's3a_16_support' = 'Other medical';
                                    's3b_1_support' = 'Assault';
                                    's3b_2_support' = 'Property destruction';
                                    's3b_3_support' = 'Stealing';
                                    's3b_4_support' = 'Self injury';
                                    's3b_5_support' = 'Pica';
                                    's3b_6_support' = 'Suicide attempts';
                                    's3b_7_support'  = 'Sexual aggression';
                                    's3b_8_support' = 'Inappropriate';
                                    's3b_9_support' = 'Outbursts';
                                    's3b_10_support' = 'Wandering';
                                    's3b_11_support' = 'Substance abuse';
                                    's3b_12_support' = 'Mental health tx';
                                    's3b_13_support' = 'Other behavioral'"),
                 level = car::recode(score,
                                     "0 = 'No Support Needed';
                                     1 = 'Some Support Needed';
                                     2 = 'Extensive Support Needed'")) 
        
      })
      
      boxInput <- reactive({
        
        sisInput() %>%
          filter(current_int == T) %>%
          droplevels() %>%
          select(interviewer,
                 fake_id,
                 medical = s3a_Score_Total,
                 behavior = s3b_Score_Total,
                 homeliving = homeliving_std,
                 commliving = commliving_std,
                 hlthsafety = hlthsafety_std,
                 lifelearng = lifelearng_std,
                 employment = employment_std,
                 social = social_std,
                 ABE = ABE_std,
                 SupportNeedsIndex) %>%
          gather(subscale, score, medical:SupportNeedsIndex) %>%
          mutate(subscale = car::recode(subscale, 
                                        "'medical' = '3a Medical Supports';
                                        'behavior' = '3b Behavioral Supports';
                                        'homeliving' = '1a Home Living';
                                        'commliving' = '1b Community Living';
                                        'hlthsafety' = '1e Health and Safety';
                                        'lifelearng' = '1c Lifelong Learning';
                                        'employment' = '1d Employment';
                                        'social' = '1f Social Activities';
                                        'ABE' = 'ABE Score';
                                        'SupportNeedsIndex' = 'Support Needs Index'"))
        
      })
      
      ## REACTIVE UI ELEMENTS ## 
      
      output$valid_date <- renderText({
        
        validate(
          need(input$dateRange[2] > input$dateRange[1], 
               "End date is earlier than start date"
          )
        )
        
        # make sure greater than 2 week difference
        validate(
          need(difftime(input$dateRange[2], input$dateRange[1], 
                        "days") > 14, "Date range less the 14 days"
          )
        )
        
        # make sure last date is in dataset range
        validate(
          need(input$dateRange[2] <= max(as.Date(scrub_sis$sis_date)[as.Date(scrub_sis$sis_date) <= Sys.Date()]), 
               "End date beyond available data"
          )
        )
        
        # make sure last date is in dataset range
        validate(
          need(input$dateRange[1] >= min(as.Date(scrub_sis$sis_date)[as.Date(scrub_sis$sis_date) <= Sys.Date()]), 
               "Start date precedes available data"
          )
        )
        
        paste("Your date range is", 
              difftime(input$dateRange[2], input$dateRange[1], units="days"),
              "days")
        
      })
      
      output$s1domain <- renderUI({
        tos1 <- tos1Input()
        selectInput("s1domain",
                    label = "Select a life domain:",
                    choices = levels(unique(as.factor(tos1$field))), 
                    selected = "")
      })
      
      output$s2domain <- renderUI({
        tos2 <- tos2Input()
        selectInput("s2domain",
                    label = "Select a life domain:",
                    choices = levels(unique(as.factor(tos2$field))), 
                    selected = "")
      })
      
      output$box_opts <- renderUI({
        
        # Make subset for subscale selection
        box_sis <- boxInput()
        selectInput("box",
                    label = "Select a subscale/area:",
                    choices = levels(as.factor(box_sis$subscale)), 
                    selected = "Support Needs Index")
        
      })
      
      ## VISUALIZATIONS ##

      output$rate <- renderValueBox({
        
        # Proportion of days in selected timeframe 
        # to days between initial date selected & due date
        elapse <- 
          as.numeric(as.POSIXct(input$dateRange[2]) - as.POSIXct(input$dateRange[1])) / 
          as.numeric(as.POSIXct(due) - as.POSIXct(input$dateRange[1])) * 100
        
        # Filter out expired assessments (> 3 yrs old)
        
        most_recent <- max(as.Date(scrub_sis$sis_date)[as.Date(scrub_sis$sis_date) <= Sys.Date()]) 
        
        sisIn <- sisInput() %>% filter(most_recent - as.Date(sis_date) <= (365 * 3))
        
        # Proportion of clients interviewed in selected time period 
        # to total current clients meeting criteria
        
        if ( input$agency == "All" ) {
          pct <- 
            nlevels(as.factor(sisIn$fake_id)) /
            totals$total[totals$agency == input$agency] * 100
          
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          assessed <- sisIn %>% filter(agency == input$agency) %>% 
            summarize(n = n_distinct(fake_id))
          
          pct <- 
            assessed$n /
            totals$total[totals$agency == input$agency] * 100
          
        } else
          print(paste0("Error.  Unrecognized input."))
        
        rate <- pct / elapse * 100
        
        valueBox(
          paste0(round(rate, digits = 1), "%"), "Completion Rate", 
          icon = icon(ifelse(rate >= 100,
                             yes = "thumbs-up",
                             no = "thumbs-down")),
          color = ifelse(rate >= 100,
                         yes = "green",
                         no = "red")
        )
        
      })
      
      output$complete <- renderValueBox({
        
        # Filter out expired assessments (> 3 yrs old)
        most_recent <- max(as.Date(scrub_sis$sis_date)[as.Date(scrub_sis$sis_date) <= Sys.Date()]) 
        
        sisIn <- sisInput() %>% filter(most_recent - as.Date(sis_date) <= (365 * 3))
        
        if ( input$agency == "All" ) {
          pct <- 
            nlevels(as.factor(sisIn$fake_id)) /
            totals$total[totals$agency == input$agency] * 100
        } else if ( input$agency %in% levels(unique(sisIn$agency)) ) {
          assessed <- sisIn %>% filter(agency == input$agency) %>% 
            summarize(n = n_distinct(fake_id))
          
          pct <- 
            assessed$n /
            totals$total[totals$agency == input$agency] * 100
        } else
          print(paste0("Error.  Unrecognized input."))
        
        valueBox(
          paste0(round(pct, digits = 1), "%"), "Complete", 
          icon = icon("pie-chart"),
          color = "teal")
        
      })
      
      output$needperwk <- renderValueBox({
        
        # Filter out expired assessments (> 3 yrs old)
        most_recent <- max(as.Date(scrub_sis$sis_date)[as.Date(scrub_sis$sis_date) <= Sys.Date()]) 
        
        sisIn <- sisInput() %>% filter(most_recent - as.Date(sis_date) <= (365 * 3))
        
        if ( input$agency == "All" ) {
          per_wk <- 
            sisIn %>%
            group_by(sis_yrwk) %>%
            summarize(n = n()) %>%
            rename(week = sis_yrwk) %>%
            mutate(avg = NA,
                   need = NA) %>%
            ungroup()
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          per_wk <- 
            sisIn %>%
            filter(agency == input$agency) %>%
            group_by(sis_yrwk) %>%
            summarize(n = n()) %>%
            rename(week = sis_yrwk) %>%
            mutate(avg = NA,
                   need = NA) %>%
            ungroup()
        } else
          print(paste0("Error.  Unrecognized input."))
        
        avgperwk <- round(mean(per_wk$n,na.rm = T), digits = 0)
        
        week <- seq(from = input$dateRange[1], to = due, by = "week")
        
        already <- nlevels(as.factor(scrub_sis$fake_id[scrub_sis$agency == input$agency
                                                       & as.Date(scrub_sis$sis_date) < input$dateRange[1]]))
        
        needed <- ceiling((totals$total[totals$agency == input$agency] 
                           - already) / length(week))
        
        valueBox(
          paste0(round(avgperwk, digits = 1), ":",
                 round(needed, digits = 1), " per week"), 
          "Assessments Completed:Needed", 
          icon = icon("file-text"),
          color = "teal")
        
      })
      
      output$num_dt <- renderDataTable({
        
        scrub_sis %<>% filter(as.Date(sis_date) >= input$dateRange[1]
                              & as.Date(sis_date) <= input$dateRange[2])
        
        if ( input$agency == "All" ) {
          num <-
            scrub_sis %>% 
            filter(current_int == T) %>% 
            droplevels() %>%
            group_by(interviewer, agency) %>%
            summarize(n = n(),
                      avg_dur = round(mean(duration, na.rm = T), digits = 0),
                      first = min(as.POSIXct(sis_date))
            ) %>% ungroup()
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          num <-
            scrub_sis %>% 
            filter(current_int == T, agency == input$agency) %>% 
            droplevels() %>%
            group_by(interviewer, agency) %>%
            summarize(n = n(),
                      avg_dur = round(mean(duration, na.rm = T), digits = 0),
                      first = min(as.POSIXct(sis_date))
            ) %>% ungroup()
        } else
          print(paste0("Error.  Unrecognized input."))
        
        
        num %>%
          datatable(caption = 'SIS assessment summary by Interviewer.',
                    rownames = FALSE,
                    colnames = c('Interviewer','Agency',
                                 '# Assessments','Avg minutes',
                                 'Interviewing since'),
                    extensions = c('Responsive','ColVis'),
                    options = list(pageLength = 5, lengthMenu = c(5, 15),
                                   dom = 'C<"clear">lfrtip')) %>%
          formatDate(5)
      })

      output$on_track <- renderDygraph({
        
        most_recent <- max(as.Date(scrub_sis$sis_date)[as.Date(scrub_sis$sis_date) <= Sys.Date()]) 
        
        if ( input$agency == "All" ) {
          
          per_wk <- 
            scrub_sis %>%
            # Filter out expired assessments (> 3 yrs old)
            filter(most_recent - as.Date(sis_date) <= (365 * 3)) %>%
            # Note we still use unfiltered dataset here to calc cum sum over wks
            filter(as.POSIXct(sis_date) >= as.POSIXct("2011-12-12")
                   & as.Date(sis_date) <= Sys.Date()
            ) %>%
            group_by(sis_yrwk) %>%
            summarize(n = n()) %>%
            rename(week = sis_yrwk) %>%
            mutate(avg = NA,
                   need = NA) %>%
            ungroup()
          
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          per_wk <- 
            scrub_sis %>%
            # Filter out expired assessments (> 3 yrs old)
            filter(most_recent - as.Date(sis_date) <= (365 * 3)) %>%
            filter(as.POSIXct(sis_date) >= as.POSIXct("2011-12-12")
                   & as.Date(sis_date) <= Sys.Date()
                   & agency == input$agency
            ) %>%
            group_by(sis_yrwk) %>%
            summarize(n = n()) %>%
            rename(week = sis_yrwk) %>%
            mutate(avg = NA,
                   need = NA) %>%
            ungroup()
        } else
          print(paste0("Error.  Unrecognized input."))
        
        week <- seq(from = max(as.Date(per_wk$week)), to = due, by = "week")
        
        # Make projection data
        tst <- data.frame(week)
        tst$n <- NA
        tst$avg <- 
          seq(from = sum(per_wk$n, na.rm = T) +
                round(mean(per_wk$n[as.POSIXct(per_wk$week) >= as.POSIXct(most_recent - 90) ], 
                           na.rm = T), 
                      digits = 0),
              to = sum(per_wk$n, na.rm = T) +
                round(mean(per_wk$n[as.POSIXct(per_wk$week) >= as.POSIXct(most_recent - 90) ], 
                           na.rm = T), 
                      digits = 0) *
                length(week),
              by = round(mean(per_wk$n[as.POSIXct(per_wk$week) >= as.POSIXct(most_recent - 90) ], 
                              na.rm = T), 
                         digits = 0)
          )
        tst$need <- 
          seq(from = sum(per_wk$n, na.rm = T) +
                ceiling((totals$total[totals$agency == input$agency] 
                         - sum(per_wk$n, na.rm = T)) / length(week)),
              to = sum(per_wk$n, na.rm = T) +
                ceiling((totals$total[totals$agency == input$agency] 
                         - sum(per_wk$n, na.rm = T)) / length(week)) *length(week),
              by = ceiling((totals$total[totals$agency == input$agency] 
                            - sum(per_wk$n, na.rm = T)) / length(week))
          )
        
        per_wk$week <- as.Date(per_wk$week) # Make date types the same
        
        per_wk <- rbind(per_wk,tst)
        
        per_wk <-
          per_wk %>%
          ungroup() %>%
          mutate(running = order_by(week, cumsum(n))) 
        
        per_wk$week <- as.POSIXct(per_wk$week)
        
        per_wk_srs <- as.xts(per_wk$running, order.by=per_wk$week)
        
        names(per_wk_srs)[1]<-"running"
        
        per_wk_srs$avg <- per_wk$avg
        per_wk_srs$need <- per_wk$need
        
        dygraph(per_wk_srs, main = "Cumulative SIS assessments") %>%
          dyAxis("x", label = "Week of Assessments") %>%
          dyAxis("y", label = "# SIS assessments (cumulative)",
                 valueRange = c(0, max(per_wk$need))) %>%
          dySeries("running", label = "Actual", 
                   strokeWidth = 2, fillGraph = TRUE) %>%
          dySeries("avg", label = "If avg continues",
                   strokeWidth = 2, strokePattern = "dashed") %>%
          dySeries("need", label = "To meet goal",
                   strokeWidth = 2, strokePattern = "dashed") %>%
          dyLegend(width = 400) %>%
          dyEvent(x = "2012-01-22", "Ottawa Starts", labelLoc = "bottom") %>%
          dyEvent(x = "2014-07-01", "Region Starts", labelLoc = "bottom") %>%
          dyEvent(x = "2017-09-20", "Deadline", labelLoc = "bottom") %>%
          dyRangeSelector(dateWindow = c(as.Date(input$dateRange[1]), as.Date(due)))
        
      })

      output$plans <- renderPlotly({
        
        if ( input$agency == "All" ) {
          
          plans <-
            sisInput() %>%
            select(fake_id, s2_Score_One, s2_Score_Two, s2_Score_Three, s2_Score_Four) %>%
            gather(rank, item, s2_Score_One:s2_Score_Four) %>%
            mutate(item = gsub(".*:","",item),
                   item = sub("^\\s+", "", item)) %>%
            group_by(item) %>%
            summarize(n = n()) %>%
            arrange(desc(n))
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          plans <-
            sisInput() %>%
            filter(agency == input$agency) %>%
            select(fake_id, s2_Score_One, s2_Score_Two, s2_Score_Three, s2_Score_Four) %>%
            gather(rank, item, s2_Score_One:s2_Score_Four) %>%
            mutate(item = gsub(".*:","",item),
                   item = sub("^\\s+", "", item)) %>%
            group_by(item) %>%
            summarize(n = n()) %>%
            arrange(desc(n))
        } else
          print(paste0("Error.  Unrecognized input."))
        
        ggplans <-
          ggplot(plans, aes(x = reorder(item,-n), y = n)) + 
          geom_bar(stat = "identity", position = "stack") +
          scale_x_discrete(breaks=NULL) +
          ylab("# times included in planning") +
          xlab("Item (hover for name)") +
          theme_bw()
        
        ggplotly(ggplans)
        
      })

      output$plans_s1 <- renderPlotly({
        
        if ( input$agency == "All" ) {
          filt_inpt <- sisInput() 
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          filt_inpt <- sisInput() %>% filter(agency == input$agency) 
        } else
          print(paste0("Error.  Unrecognized input."))
        
        plans_s1 <-
          filt_inpt %>%
          select(fake_id, contains("s1")) %>%
          select(fake_id, ends_with("to"), ends_with("for")) %>%
          gather(field, score, s1a_1_to:s1f_8_for) %>%
          mutate(important = ifelse(grepl("to$", field), yes = "To", no = "For"),
                 item = gsub("to|for", "", field)) %>%
          group_by(item, important) %>%
          summarize(n = sum(score)) %>%
          arrange(desc(n)) %>%
          ungroup() %>%
          mutate(item = car::recode(item,
                                    "'s1a_1_' = 'Toilet';
                                    's1a_2_' = 'Clothes';
                                    's1a_3_' = 'Preparing food';
                                    's1a_4_' = 'Eating food';
                                    's1a_5_' = 'Housekeeping';
                                    's1a_6_' = 'Dressing';
                                    's1a_7_' = 'Hygiene';
                                    's1a_8_' = 'Appliances';
                                    's1b_1_' = 'Getting Around';
                                    's1b_2_' = 'Recreation';
                                    's1b_3_' = 'Public Services';
                                    's1b_4_' = 'Visit Friends/Family';
                                    's1b_5_' = 'Preferred Activities';
                                    's1b_6_' = 'Shopping';
                                    's1b_7_' = 'Community interaction';
                                    's1b_8_' = 'Accessing Settings';
                                    's1c_1_' = 'Learning interaction';
                                    's1c_2_' = 'Learning decisions';
                                    's1c_3_' = 'Problem solving';
                                    's1c_4_' = 'Using technology';
                                    's1c_5_' = 'Accessing training';
                                    's1c_6_' = 'Academics';
                                    's1c_7_' = 'Learning health skills';
                                    's1c_8_' = 'Learning self-determination';
                                    's1c_9_' = 'Learning self-management';
                                    's1d_1_' = 'Job accomodations';
                                    's1d_2_' = 'Specific job skills';
                                    's1d_3_' = 'Co-worker interaction';
                                    's1d_4_' = 'Supervisor interaction';
                                    's1d_5_' = 'Work speed';
                                    's1d_6_' = 'Work quality';
                                    's1d_7_' = 'Changing assignments';
                                    's1d_8_' = 'Seeking assistance';
                                    's1e_1_' = 'Taking medications';
                                    's1e_2_' = 'Avoiding hazards';
                                    's1e_3_' = 'Obtaining health care';
                                    's1e_4_' = 'Moving about';
                                    's1e_5_' = 'Accessing emergency svs';
                                    's1e_6_' = 'Nutritional diet';
                                    's1e_7_' = 'Physical fitness';
                                    's1e_8_' = 'Emotional well-being';
                                    's1f_1_' = 'Socializing in home';
                                    's1f_2_' = 'Recreation with others';
                                    's1f_3_' = 'Socializing out of home';
                                    's1f_4_' = 'Making friends';
                                    's1f_5_' = 'Communicating with helpers';
                                    's1f_6_' = 'Appropriate social skills';
                                    's1f_7_' = 'Intimate relationships';
                                    's1f_8_' = 'Volunteer work'"))

          ggplans <-
            ggplot(plans_s1, aes(x = reorder(item,-n), y = n, fill = important)) + 
            geom_bar(stat = "identity", position = "stack") +
            scale_x_discrete(breaks=NULL) +
            scale_fill_manual(values = c('#b2df8a', '#1f78b4')) + 
            ylab("People with need marked as important") +
            xlab("Life Domain") +
            theme_bw()
          
          ggplotly(ggplans)
        
      })

      output$tos_s1 <- renderParset({
        
        if ( input$agency == "All" ) {
          tos_parset <- 
            tos1Input() %>% 
            filter(field == input$s1domain) %>%
            select(-field) %>%
            group_by(type,frequency,DST,agency) %>%
            summarize(n = sum(n))
          
          parset(
            tos_parset,
            # dimensions are the categorical columns
            dimensions = colnames(tos_parset)[-5],
            # use some JavaScript to inform parset that Freq has the value
            value = htmlwidgets::JS("function(d){return d.n}"),
            tension = 0.5,
            width = "80%", height = 400
          )
          
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          tos_parset <- 
            tos1Input() %>% 
            filter(agency == input$agency 
                   & field == input$s1domain) %>%
            group_by(type,frequency,DST) %>%
            summarize(n = sum(n))
          
          parset(
            tos_parset,
            # dimensions are the categorical columns
            dimensions = colnames(tos_parset)[-4],
            # use some JavaScript to inform parset that Freq has the value
            value = htmlwidgets::JS("function(d){return d.n}"),
            tension = 0.5,
            width = "80%", height = 400
          )
        } else
          print(paste0("Error.  Unrecognized input."))
        
      })
      
      output$tos_s2 <- renderParset({
        
        if ( input$agency == "All" ) {
          tos_parset <- 
            tos2Input() %>% 
            filter(field == input$s2domain) %>%
            select(-field) %>%
            group_by(agency,type,frequency,DST) %>%
            summarize(n = sum(n))
          
          parset(
            tos_parset,
            # dimensions are the categorical columns
            dimensions = colnames(tos_parset)[-5],
            # use some JavaScript to inform parset that Freq has the value
            value = htmlwidgets::JS("function(d){return d.n}"),
            tension = 0.5,
            width = "80%", height = 400
          )
          
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          tos_parset <- 
            tos2Input() %>% 
            filter(agency == input$agency 
                   & field == input$s2domain) %>%
            group_by(type,frequency,DST) %>%
            summarize(n = sum(n))
          
          parset(
            tos_parset,
            # dimensions are the categorical columns
            dimensions = colnames(tos_parset)[-4],
            # use some JavaScript to inform parset that Freq has the value
            value = htmlwidgets::JS("function(d){return d.n}"),
            tension = 0.5,
            width = "80%", height = 400
          )
          
        } else
          print(paste0("Error.  Unrecognized input."))
        
      })

      output$s1_dt <- renderDataTable({
        
        if ( input$agency == "All" ) {
          
          df <-
            sec1Input() %>%
            group_by(agency, item) %>%
            summarize(avg = round(mean(score), digits = 1)) %>%
            spread(agency, avg)
          
          dt_in <-
            sec1Input() %>%
            group_by(item) %>%
            summarize(avg = round(mean(score), digits = 1)) %>% 
            left_join(df, id = "item") %>%
            rename(All = avg)
          
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          
          df <-
            sec1Input() %>%
            group_by(agency, item) %>%
            summarize(avg = round(mean(score), digits = 1)) %>%
            filter(agency == input$agency) %>%
            spread(agency, avg)
          
          dt_in <-
            sec1Input() %>%
            filter(agency != input$agency) %>%
            group_by(item) %>%
            summarize(avg = round(mean(score), digits = 1)) %>% 
            left_join(df, id = "item") %>%
            rename(All.Others = avg)
          
        } else
          print(paste0("Error.  Unrecognized input."))
        
        dt_in %>%
          datatable(caption = 'Average Raw Scores on Section 1 Items, by CMH',
                    rownames = FALSE,
                    extensions = c('Responsive','ColVis'),
                    options = list(pageLength = 5,
                                   lengthMenu = c(5, 10, nlevels(as.factor(dt_in$item))),
                                   dom = 'C<"clear">lfrtip')) 
      })
       
      output$s2_dt <- renderDataTable({
        
        if ( input$agency == "All" ) {
          
          df <-
            sec2Input() %>%
            group_by(agency, item) %>%
            summarize(avg = round(mean(score), digits = 1)) %>%
            spread(agency, avg)
          
          dt_in <-
            sec2Input() %>%
            group_by(item) %>%
            summarize(avg = round(mean(score), digits = 1)) %>% 
            left_join(df, id = "item") %>%
            rename(All = avg)
          
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          
          df <-
            sec2Input() %>%
            group_by(agency, item) %>%
            summarize(avg = round(mean(score), digits = 1)) %>%
            filter(agency == input$agency) %>%
            spread(agency, avg)
          
          dt_in <-
            sec2Input() %>%
            filter(agency != input$agency) %>%
            group_by(item) %>%
            summarize(avg = round(mean(score), digits = 1)) %>% 
            left_join(df, id = "item") %>%
            rename(All.Others = avg)
          
        } else
          print(paste0("Error.  Unrecognized input."))
        
        
        dt_in %>%
          datatable(caption = 'Average Raw Scores on Section 2 Items, by CMH',
                    rownames = FALSE,
                    extensions = c('Responsive','ColVis'),
                    options = list(pageLength = nlevels(as.factor(dt_in$item)), 
                                   dom = 'C<"clear">lfrtip')) 
      })
      
      output$hist_sni <- renderPlotly({
        
        if ( input$agency == "All" ) {
          hist <-
            ggplot(sisInput(), aes(x = SupportNeedsIndex, fill = agency)) +
            geom_histogram(alpha = .5, binwidth = 2, position = "stack") +
            scale_x_continuous(name = "Support Needs Index") +
            scale_y_continuous(name = "Number of Clients") +
            scale_fill_discrete(name = "CMHSP") + 
            theme_bw()
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          scrub_sis_filt <- sisInput() %>% filter(agency == input$agency)
          hist <-
            ggplot(scrub_sis_filt, aes(x = SupportNeedsIndex, fill = agency)) +
            geom_histogram(alpha = .5, binwidth = 2) + 
            scale_x_continuous(name = "Support Needs Index") +
            scale_y_continuous(name = "Number of Clients") +
            scale_fill_discrete(name = "CMHSP") +
            scale_fill_discrete(name = "CMHSP") + 
            theme_bw()
        } else
          print(paste0("Error.  Unrecognized input."))
        
        ifelse(
          input$central == "Mean",
          yes = hist <-hist + geom_vline(data = scrub_sis, 
                                         aes(xintercept = mean(SupportNeedsIndex)),
                                         linetype = "dashed", size = 0.5),
          no  = hist <-hist + geom_vline(data = scrub_sis, 
                                         aes(xintercept = median(SupportNeedsIndex)),
                                         linetype = "dashed", size = 0.5)
        )
        
        ggplotly(hist)
        
      })

      output$norm_sni <- renderPlotly({
        
        if ( input$agency == "All" ) {
          scrub_sis_filt <- sisInput()
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          scrub_sis_filt <- sisInput() %>% filter(agency == input$agency)
        } else
          print(paste0("Error.  Unrecognized input."))
        
        p <- 
          qplot(scrub_sis_filt$SupportNeedsIndex, geom = 'blank') +
          geom_histogram(aes(y = ..density..), alpha = 0.5) +
          geom_line(aes(y = ..density.., colour = 'Actual Scores'), stat = 'density') +
          stat_function(fun = "dnorm", args = c(100, 15), aes(colour = 'Standard Scores'))  +
          scale_colour_manual(name = '', values = c('#00A08A', '#F98400')) + 
          theme(legend.position = 'top', legend.direction = 'horizontal') +
          theme_bw() + 
          scale_x_continuous(name = "Support Needs Index") +
          scale_y_continuous(name = "Density") 
        
        ggplotly(p)
        
      })
        
      output$dt_sni <- renderDataTable({
        
        if ( input$agency == "All" ) {
          clin_by_dom <-
            sisInput() %>%
            select(agency = agency,
                   medical = s3a_Score_Total,
                   behavior = s3b_Score_Total,
                   homeliving = homeliving_std,
                   commliving = commliving_std,
                   hlthsafety = hlthsafety_std,
                   lifelearng = lifelearng_std,
                   employment = employment_std,
                   social = social_std) %>%
            group_by(agency) %>%
            summarize(n = n(),
                      medical = round(mean(medical), digits = 1),
                      behavior = round(mean(behavior), digits = 1),
                      homeliving = round(mean(homeliving), digits = 1),
                      commliving = round(mean(commliving), digits = 1),
                      hlthsafety = round(mean(hlthsafety), digits = 1),
                      lifelearng = round(mean(lifelearng), digits = 1),
                      employment = round(mean(employment), digits = 1),
                      social = round(mean(social), digits = 1)) %>%
            select(agency, medical:social)
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          clin_by_dom <-
            sisInput() %>%
            filter(agency == input$agency) %>%
            select(agency = agency,
                   medical = s3a_Score_Total,
                   behavior = s3b_Score_Total,
                   homeliving = homeliving_std,
                   commliving = commliving_std,
                   hlthsafety = hlthsafety_std,
                   lifelearng = lifelearng_std,
                   employment = employment_std,
                   social = social_std) %>%
            group_by(agency) %>%
            summarize(n = n(),
                      medical = round(mean(medical), digits = 1),
                      behavior = round(mean(behavior), digits = 1),
                      homeliving = round(mean(homeliving), digits = 1),
                      commliving = round(mean(commliving), digits = 1),
                      hlthsafety = round(mean(hlthsafety), digits = 1),
                      lifelearng = round(mean(lifelearng), digits = 1),
                      employment = round(mean(employment), digits = 1),
                      social = round(mean(social), digits = 1)) %>%
            select(agency, medical:social)
        } else
          print(paste0("Error.  Unrecognized input."))
        
        clin_by_dom %>%
          datatable(rownames = FALSE,
                    colnames = c('Agency',
                                 'Medical','Behavioral',
                                 'Home','Community','Safety',
                                 'Learning','Employment', 'Social'),
                    caption = 'Average subscale scores by Agency',
                    extensions = c('Responsive','ColVis'),
                    options = list(pageLength = 5, lengthMenu = c(5, 10, 20),
                                   dom = 'C<"clear">lfrtip')) %>%
          formatStyle('medical',
                      background = styleColorBar(clin_by_dom$medical, 'lightseagreen'),
                      backgroundSize = '100% 90%',
                      backgroundRepeat = 'no-repeat',
                      backgroundPosition = 'center') %>%
          formatStyle('behavior',
                      background = styleColorBar(clin_by_dom$behavior, 'lightsteelblue'),
                      backgroundSize = '100% 90%',
                      backgroundRepeat = 'no-repeat',
                      backgroundPosition = 'center') %>%
          formatStyle('homeliving',
                      background = styleColorBar(clin_by_dom$homeliving, 'lightblue'),
                      backgroundSize = '100% 90%',
                      backgroundRepeat = 'no-repeat',
                      backgroundPosition = 'center') %>%
          formatStyle('commliving',
                      background = styleColorBar(clin_by_dom$commliving, 'steelblue'),
                      backgroundSize = '100% 90%',
                      backgroundRepeat = 'no-repeat',
                      backgroundPosition = 'center') %>%
          formatStyle('hlthsafety',
                      background = styleColorBar(clin_by_dom$hlthsafety, 'darkseagreen'),
                      backgroundSize = '100% 90%',
                      backgroundRepeat = 'no-repeat',
                      backgroundPosition = 'center') %>%
          formatStyle('lifelearng',
                      background = styleColorBar(clin_by_dom$lifelearng, 'darkcyan'),
                      backgroundSize = '100% 90%',
                      backgroundRepeat = 'no-repeat',
                      backgroundPosition = 'center') %>%
          formatStyle('employment',
                      background = styleColorBar(clin_by_dom$employment, 'mediumturquoise'),
                      backgroundSize = '100% 90%',
                      backgroundRepeat = 'no-repeat',
                      backgroundPosition = 'center') %>%
          formatStyle('social',
                      background = styleColorBar(clin_by_dom$social, 'mediumaquamarine'),
                      backgroundSize = '100% 90%',
                      backgroundRepeat = 'no-repeat',
                      backgroundPosition = 'center')
        
      })
      
      output$conditions <- renderPlotly({
        
        radio <- if (input$radio_mb == "Both") {c("Medical","Behavioral")
        } else if (input$radio_mb == "Medical") {c("Medical")
        } else if (input$radio_mb == "Behavioral") {c("Behavioral")
        } else print(paste0("Error.  Unrecognized input."))
        
        if ( input$agency == "All" ) {
          conditions <-
            sec3Input() %>%
            filter(score > 0
                   & type %in% radio
                   & LivingType %in% input$living) %>%
            group_by(name,level) %>%
            summarize(n = n()) %>%
            arrange(desc(n))
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) ) {
          conditions <-
            sec3Input() %>%
            filter(agency == input$agency
                   & score > 0
                   & type %in% radio
                   & LivingType %in% input$living) %>%
            group_by(name,level) %>%
            summarize(n = n()) %>%
            arrange(desc(n))
        } else
          print(paste0("Error.  Unrecognized input."))
        
        gg3 <-
          ggplot(conditions, aes(x = reorder(name,-n), y = n, fill = level)) + 
          geom_bar(stat = "identity", position = "stack") +
          scale_x_discrete(breaks=NULL) +
          ylab("Number of people with need") +
          xlab("Type of Need") +
          theme_bw()
        
        ggplotly(gg3)
        
      })

      output$hist_mb <- renderPlotly({
        
        if ( input$agency == "All" & input$radio_mbhist == "Medical" ) {
          scrub_sis_filt <- sisInput() %>% filter(LivingType %in% input$living)
          hist <-
            ggplot(scrub_sis_filt, 
                   aes(x = s3a_Score_Total, 
                       fill = agency)) +
            geom_histogram(alpha = .5, binwidth = 1, position = "stack") +
            scale_x_continuous(name = "Medical Needs per Person") +
            scale_y_continuous(name = "Number of Clients") +
            scale_fill_discrete(name = "CMHSP") + 
            theme_bw()
        } else if ( input$agency == "All" & input$radio_mbhist == "Behavioral" ) {
          scrub_sis_filt <- sisInput() %>% filter(LivingType %in% input$living)
          hist <-
            ggplot(scrub_sis_filt, 
                   aes(x = s3b_Score_Total, 
                       fill = agency)) +
            geom_histogram(alpha = .5, binwidth = 1, position = "stack") +
            scale_x_continuous(name = "Behavioral Needs per Person") +
            scale_y_continuous(name = "Number of Clients") +
            scale_fill_discrete(name = "CMHSP") + 
            theme_bw()
        } else if ( input$agency %in% levels(unique(scrub_sis$agency))
                    & input$radio_mbhist == "Medical" ) {
          scrub_sis_filt <- 
          sisInput() %>% 
            filter(agency == input$agency 
                   & LivingType %in% input$living)
          hist <-
            ggplot(scrub_sis_filt, aes(x = s3a_Score_Total, fill = agency)) +
            geom_histogram(alpha = .5, binwidth = 1) + 
            scale_x_continuous(name = "Medical Needs per Person") +
            scale_y_continuous(name = "Number of Clients") +
            scale_fill_discrete(name = "CMHSP") +
            theme_bw()
        } else if ( input$agency %in% levels(unique(scrub_sis$agency)) 
                    & input$radio_mbhist == "Behavioral") {
          scrub_sis_filt <- 
          sisInput() %>% 
            filter(agency == input$agency
                   & LivingType %in% input$living)
          hist <-
            ggplot(scrub_sis_filt, aes(x = s3b_Score_Total, fill = agency)) +
            geom_histogram(alpha = .5, binwidth = 1) + 
            scale_x_continuous(name = "Behavioral Needs per Person") +
            scale_y_continuous(name = "Number of Clients") +
            scale_fill_discrete(name = "CMHSP") +
            theme_bw()
        } else
          print(paste0("Error.  Unrecognized input."))
        
        ggplotly(hist)
        
      })
      
      output$box_int <- renderPlotly({
        
        # Make an interviewer key
        box_df <- boxInput() 
        int_nm <- unique(box_df$interviewer)
        int_id <- c() #create an empty vec
        n <- 1 # Set initial num
        for (i in unique(box_df$interviewer)) {
          int_id <- c(int_id,
                      paste0("Interviewer ", 
                             as.character(n)))
          n <- n + 1
        }
        int_df <- data.frame(int_nm)
        int_df <- int_df %>% arrange(int_nm)
        int_df$int_id <- as.factor(int_id)
        rm(int_id); rm(int_nm)
        
        boxInput() %>%
          left_join(int_df, by = c("interviewer" = "int_nm")) %>%
          filter(subscale == input$box) %>%
          plot_ly(x = score, color = int_id, type = "box") %>%
          plotly::layout(yaxis = list(title = "Interviewers",
                                      showticklabels = F))
          
      })
      
      output$need_heat <- renderD3heatmap({
        
        heat <- 
          sisInput() %>%
          filter(is.na(fake_id) == FALSE) %>% # Remove empty randomized IDs
          group_by(fake_id) %>% 
          filter(as.Date(sis_date) == max(as.Date(sis_date))) %>% # Most recent per ID
          ungroup() %>% droplevels() %>%
          select(homeliving_std,commliving_std,hlthsafety_std,
                 lifelearng_std,social_std,self_advoc:other_advoc,s3a_Score_Total,
                 s3b_Score_Total) %>%
          rename(home = homeliving_std, 
                 community = commliving_std,
                 health_safety = hlthsafety_std, 
                 learning = lifelearng_std,
                 social = social_std, 
                 self_advocacy = self_advoc,
                 other_advocacy = other_advoc,
                 medical = s3a_Score_Total,
                 behavioral = s3b_Score_Total) %>%
          mutate_each(funs(as.numeric)) %>%
          scale() 
        
        d3heatmap(heat, 
                  colors = "Blues",
                  k_row = input$need_rows, k_col = input$need_cols,
                  theme = "",
                  yaxis_font_size =  "0pt",
                  show_grid = F)
        
      })
      
    }
  )